### PR TITLE
Avoid the robot to step in place in case the minAngle is less than the feetYawDelta.

### LINKED ISSUE #42: The robot may step in place when using the feetYawDelta and a minimum angle small enough
It seems that the terminal step mechanism is triggered when using the ``feetYawDelta``. This causes the robot to step in place.

### PR DESCRIPTION
**Pull request by S-Dafarra**
Fixes #42 

I have tested it in simulation. 

Instead of computing the difference in the orientation using directly the yaw of the foot, I consider the corresponding unicycle angle (after removing the delta).

### CODE REVIEW

**Comment by S-Dafarra** [comment]
In the first version of this PR there was a bug. When computing the difference between the current unicycle angle, and the stance foot, this latter quantity was never updated even if new steps were added. Hence, it was always taking only step when turning. Afterwards, the constraint on the maximum angle was (obviously) failing. Apart from this problem, the interesting thing was that the robot feet were not becoming parallel after the failure of the constraints. I got puzzled by this, so I dig into the code and I found a series of other problems fixed by https://github.com/robotology/unicycle-footstep-planner/pull/44/commits/c9773d5206cdba82a0e40e331d61210179618da7.

Hence, I took the occasion to do also a bit of cleanup.

I did a couple of more tests in simulation. But it may be worth checking this on a real platform.

**Comment by S-Dafarra** [comment]
> I did a couple of more tests in simulation. But it may be worth checking this on a real platform.

@GiulioRomualdi and @isorrentino quickly tested it on the robot. @GiulioRomualdi I think this is ready to be reviewed/merged.

**Comment by S-Dafarra** [comment]
> > I did a couple of more tests in simulation. But it may be worth checking this on a real platform.
> 
> @GiulioRomualdi and @isorrentino quickly tested it on the robot. @GiulioRomualdi I think this is ready to be reviewed/merged.

Friendly ping @GiulioRomualdi

**Comment by S-Dafarra** [comment]
> > > I did a couple of more tests in simulation. But it may be worth checking this on a real platform.
> > 
> > 
> > @GiulioRomualdi and @isorrentino quickly tested it on the robot. @GiulioRomualdi I think this is ready to be reviewed/merged.
> 
> Friendly ping @GiulioRomualdi

Friendly ping @GiulioRomualdi :grin:

**Comment by S-Dafarra** [comment]
> > > > I did a couple of more tests in simulation. But it may be worth checking this on a real platform.
> > > 
> > > 
> > > @GiulioRomualdi and @isorrentino quickly tested it on the robot. @GiulioRomualdi I think this is ready to be reviewed/merged.
> > 
> > 
> > Friendly ping @GiulioRomualdi
> 
> Friendly ping @GiulioRomualdi

Friendly ping @GiulioRomualdi. We should try to close this by the end of this sprint

**Review by GiulioRomualdi — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
I rewired the PR and it seems ok. Furthermore, last week I run the walking several time on the robot and everything went fine

**Comment by S-Dafarra** [comment]
> I rewired the PR and it seems ok. Furthermore, last week I ran the walking several time on the robot and everything went fine

Great, thanks!

**Pull request merged**
