### PR TITLE
Merge devel branch in master

### PR DESCRIPTION
**Pull request by S-Dafarra**
cc @GiulioRomualdi, @traversaro, @aikolina

This merge will deprecate the previous ``UnicyclePlanner`` interface. Please check if this breaks your pipeline. Refer to me to migrate from one interface to the other.

### CODE REVIEW

**Comment by traversaro** [comment]
Even if in the master you are not exporting the version number in CMake configuration file, I suggest to make a release/tag of the latest commit with the old branch, so that if anyone has any problem, it would be trivial to switch to the "old version". 
Furthermore, is the old interface "deprecated" (i.e. it is still there with the same API, its use is just discouraged because it will be eventually changed/removed) or it is actually have been changed/removed (I understood that the change was breaking)? For research grade software I see no problem in breaking changes, but if that it is the case the PR should mention it, and not say that the old interface is "deprecated".

**Comment by traversaro** [comment]
> It should not be breaking. Old interfaces should just throw warning, and this is what I want to make sure of.

Great.

**Comment by traversaro** [comment]
Thanks to @aikolina , tests with internal software went fine.

**Comment by S-Dafarra** [comment]
Thanks a lot!

**Comment by S-Dafarra** [comment]
> I suggest to make a release/tag of the latest commit with the old branch, so that if anyone has any problem, it would be trivial to switch to the "old version".

Tag available [here](https://github.com/robotology/unicycle-footstep-planner/releases/tag/v0.1.0)

**Pull request merged**
