### PR TITLE
Fix tests and add CI

### PR DESCRIPTION
**Pull request by S-Dafarra**
This should fix https://github.com/robotology/robotology-superbuild/issues/1006 and hopefully avoid this to happen again

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
For me you can also drop the vcpkg/Windows CI, from my point of view conda/Windows is more then sufficient.

**Comment by S-Dafarra** [comment]
I still need to fix the compilation of ``iDynTree`` using ``vcpkg``. It is not finding ``eigen3``.

**Comment by S-Dafarra** [comment]
> For me you can also drop the vcpkg/Windows CI, from my point of view conda/Windows is more then sufficient.

Ok, I will remove it then

**Comment by S-Dafarra** [comment]
Tests are successful. @traversaro if you agree I would merge and release another version

**Comment by traversaro** [comment]
> Tests are successful. @traversaro if you agree I would merge and release another version

Ok for me!

**Pull request merged**
