### PR TITLE
Add GNUInstallDirs to CMakeLists

### PR DESCRIPTION
**Pull request by lrapetti**
Fix https://github.com/robotology/unicycle-footstep-planner/issues/29

### CODE REVIEW

**Comment by traversaro** [comment]
I am afraid it should be included before its variables are used in line 3

**Comment by lrapetti** [comment]
> I am afraid it should be included before its variables are used in line 3

Thanks @traversaro, I have updated its position in https://github.com/robotology/unicycle-footstep-planner/pull/30/commits/79a8f9915ab6f75d4112181cc9ca1fb43aae2e2a.

**Comment by GiulioRomualdi** [comment]
LGTM @s-dafarra can we merge the PR?

**Comment by S-Dafarra** [comment]
Thanks!

**Pull request merged**
