### PR TITLE
Evaluate the desired feet acceleration in the planner

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR:
* add the evaluation of the desired feet acceleration in the `FeetCubicSplineGenerator` and `FeetMinimumJerkGenerator` classes;
* update the required `iDynTree` version in the `CmakeLists.txt` file;
* update the required `iDynTree` version in the `README.md` file.

### CODE REVIEW

**Comment by S-Dafarra** [comment]
Looks good to me! Did you run any test?

**Comment by GiulioRomualdi** [comment]
> Looks good to me! Did you run any test?

Actually no, probably it's better if I update the existing test and I check the data

**Comment by GiulioRomualdi** [comment]
I updated the test and this is the result on the z-axis. The acceleration, in the case of cubic spline interpolation, is discontinuous. This problem is already known and it is related to a feature that has to be implemented in iDynTree https://github.com/robotology/idyntree/issues/405 .

zTraj

**Comment by GiulioRomualdi** [comment]
Yes we can merge

**Comment by GiulioRomualdi** [comment]
@S-Dafarra can I merge the PR?

**Comment by S-Dafarra** [comment]
Sorry for the delay, I completely forgot.

**Pull request merged**
